routes/web.php
<?php
use App\Customer;
use App\User;
use Illuminate\Mail\Markdown;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
route::get('/clear/config', function(){
		Artisan::call('config:clear');
	});

route::get('/clear/cache', function(){
	Artisan::call('cache:clear');
});

route::get('/storage/storage', function(){
	Artisan::call('storage:link');
});

Route::get('/', 'AdminController@index')->name('dashboard');
// Route::get('/', 'Dashbaord@index')->name('landing');
Route::get('/reg', function(){
	return view('auth.register');
});
Route::middleware('auth')->prefix('admin')->group(function () {


route::get('/changePassword', function(){
    $user = User::find(auth::user()->id);
	return view('auth.passwords.reset',$user);
});

Route::post('changePassword','AdminController@showChangePasswordForm')->name('changePassword');

Route::get('/mail', function(){
	return view('mail.test');
});


Route::get('/book', function(){
	return view('booking');
});


// Route::get('/mail', function () {
// 	$data['subject'] = 'test';
// 	$data['name'] = 'pwet';

// 	return view('mail.receipt', $data);
    // $markdown = new Markdown(view(), config('mail.markdown'));
    // return $markdown->render('mail.name');
// });

	Route::get('/dashapi', 'AdminController@dashBoardPaginate');

	Route::get('forbidden', function () {
		return view('layouts.dashboard.forbidden');
	});

	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


 	Route::get('/maids-schedule', 'AdminController@maids_schedule')->name('maids-schedule');
 	Route::post('/maids-itinerary', 'AdminController@maids_itinerary')->name('maids-itinerary');

	Route::post('/addMaidsItinerary', 'AdminController@addMaidsItinerary')->name('addMaidsItinerary');
	Route::post('/maids_itinerary_update', 'AdminController@maids_itinerary_update')->name('maids_itinerary_update');
	Route::post('/get_available_maids', 'AdminController@get_available_maids')->name('get_available_maids');
	
	Route::get('/drivers-schedule', 'AdminController@drivers_schedule')->name('drivers-schedule');

	Route::post('/getCountPerAreaMaids', 'AdminController@getCountPerAreaMaids')->name('getCountPerAreaMaids');
	
	Route::any('/getAreaSubArea', 'AdminController@getAreaSubArea')->name('getAreaSubArea');
	
	Route::post('getAreaOnly', 'AdminController@getAreaOnly')->name('getAreaOnly');
	
	Route::post('/getJsonRequestResource', 'AdminController@getJsonRequestResource')->name('getJsonRequestResource');
	Route::post('/getJsonRequestEvent', 'AdminController@getJsonRequestEvent')->name('getJsonRequestEvent');

	Route::post('/getAreaAndCount', 'AdminController@getAreaAndCount')->name('getAreaAndCount');
	Route::post('/getlabel', 'AdminController@getlabel')->name('getlabel');

	Route::post('/procDoneTask', 'AdminController@procDoneTask')->name('procDoneTask');

	Route::post('getamount', 'AdminController@getAmount')->name('getAmount');

	Route::post('getamountwithtax', 'AdminController@getAmountWithTax')->name('getAmountWithTax');

	//maintenance	


	Route::resource('maids', 'AdminMaids');
	Route::resource('drivers', 'AdminDrivers');
	Route::resource('customers', 'AdminCustomers');

	Route::middleware('super')->group(function () {
		//admin maids
		Route::post('/delmaids','AdminMaids@delmaids')->name('delmaids');
		//admin drivers
		Route::post('/deldriver','AdminMaids@deldriver')->name('deldriver');
		//admin users
		Route::resource('users', 'AdminUsers');
		Route::post('/delusers','AdminUsers@delusers')->name('delusers');
		//admin customers
		Route::post('/delcustomer','AdminCustomers@delcustomer')->name('delcustomer');
		Route::post('getareas','AdminCustomers@getareas')->name('getareas');
	});

	//reports
	//sales
	Route::get('/reports/sales', 'AdminSales@index');
	Route::post('year', 'AdminSales@year')->name('year');
	Route::post('week', 'AdminSales@week')->name('week');
	Route::post('month', 'AdminSales@month')->name('month');
	Route::get('/reports/now', 'AdminSales@week');

	Route::get('/sales-test', 'AdminSales@index2');
	Route::post('/daterange', 'AdminSales@dateRange')->name('daterange');
	Route::post('TranSummaryFilter', 'AdminSales@TranSummaryFilter')->name('TranSummaryFilter');
	Route::get('/reports/details', 'AdminSalesDetails@index');

	Route::get('/reports/top-customers','AdminSales@TopCustomers' );
	Route::get('/reports/top-maids','AdminSales@TopMaids' );

	Route::get('/reports/active-customers','AdminSales@ActiveCustomers' );
	Route::get('/reports/inactive-customers','AdminSales@InactiveCustomers' );

	Route::get('/reports/cancelled-appointments', function(){
        return view('parts-dashboard.admin-cancelled-appointments');
	});
	Route::post('CancelledAppoint', 'AdminSales@CancelledAppoint')->name('CancelledAppoint');

	Route::post('ActiveAjax', 'AdminSales@ActiveAjax');
	Route::get('/transactions-customers', 'AdminTransactions@CustomersView');
	Route::post('TransactionTableCustomers', 'AdminTransactions@TransactionTableCustomers')->name('TransactionTableCustomers');
	Route::get('transactions/{id}/customer-transaction','AdminTransactions@TransactionCustomerView');

	Route::get('/transactions-maids', 'AdminTransactions@MaidsView');
	Route::get('transactions/{id}/maid-transaction','AdminTransactions@TransactionMaidView');
	Route::post('TransactionTableMaids', 'AdminTransactions@TransactionTableMaids')->name('TransactionTableMaids');

	Route::get('/appointments', 'AdminBook@index')->name('appointments');
	Route::post('getCUstomerDetails', 'AdminBook@getCUstomerDetails')->name('getCUstomerDetails');
	Route::post('newAppointment', 'AdminBook@newAppointment')->name('newAppointment');
	Route::get('/maids-schedule-table', 'AdminBook@MaidsScheduleTableView');
	Route::post('MaidsScheduleTableDetail', 'AdminBook@MaidsScheduleTableDetail')->name('MaidsScheduleTableDetail');
	Route::post('MaidsScheduleTable', 'AdminBook@MaidsScheduleTable')->name('MaidsScheduleTable');
	Route::post('MaidsScheduleTableCancel', 'AdminBook@MaidsScheduleTableCancel')->name('MaidsScheduleTableCancel');
	Route::any('/MaidsScheduleRecur', 'AdminBook@MaidsScheduleRecur')->name('MaidsScheduleRecur');
	Route::post('editAppointment', 'AdminBook@editAppointment')->name('editAppointment');
	Route::post('getamountRecur', 'AdminController@getamountRecur')->name('getamountRecur');
	Route::post('/appointments', 'AdminBook@quickAdd')->name('quickAdd');
	Route::post('quickEdit', 'AdminBook@quickEdit')->name('quickEdit');

	Route::get('/cancel-appointment', function(){
		return view('parts-dashboard.admin-cancel-appointment');
	});
	
	Route::post('cancelAppointment', 'AdminBook@cancelAppointment')->name('cancelAppointment');
	Route::get('/paginate', 'AdminPaginate@index');
	Route::get('/paginate/dropdown/{id}/fullname/{name}/api', 'AdminPaginate@returnApi');
	Route::get('/paginate/getDropdown','AdminPaginate@getDropdown');
	Route::get('/paginate/maids/api','AdminPaginate@returnApiMaids');

	Route::get('/accounting', 'AdminAccounting@index');
	Route::get('/accounting-paid', 'AdminAccounting@paidView');
	Route::get('/accounting-unpaid', 'AdminAccounting@unpaidView');
	Route::post('AccountingType', 'AdminAccounting@AccountingType')->name('AccountingType');
	Route::post('AccountingTable', 'AdminAccounting@AccountingTable')->name('AccountingTable');
	Route::get('/accounting/{id}/transaction-details','AdminAccounting@TransactionDetails');
	Route::post('sendEmailAccount', 'AdminAccounting@sendEmailAccount')->name('sendEmailAccount');

	Route::post('checkBalance', 'AdminAccounting@checkBalance')->name('checkBalance');
	Route::post('savepayment', 'AdminAccounting@savepayment')->name('savepayment');
	Route::post('payAllSumId', 'AdminAccounting@payAllSumId')->name('payAllSumId');
	Route::post('payPerSumId', 'AdminAccounting@payPerSumId')->name('payPerSumId');
	Route::get('/accounting/{id}/transaction-details/pdf','AdminAccounting@exporting');

	Route::post('sendEmail', 'MailController@sendEmail')->name('sendEmail');

	Route::get('/invoice', 'AdminAccounting@invoice');
	// Route::get('/mail', 'AdminAccounting@mail');

	Route::post('sendEmailReceipt', 'AdminAccounting@sendEmailReceipt')->name('sendEmailReceipt');
	Route::post('emailCustomers', 'AdminSales@emailCustomers')->name('emailCustomers');

	Route::get('/products', function(){
		return view('parts-dashboard.admin-products');
	});



});

resources/views/dashboard.blade.php
@extends('layouts.app')



@section('content-styles')

    <!-- Custom CSS -->

    <link href="{{ asset('dashtemplate/css/lib/chartist/chartist.min.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/lib/calendar2/semantic.ui.min.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/lib/calendar2/pignose.calendar.min.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/lib/owl.carousel.min.css') }}" rel="stylesheet" />

    <link href="{{ asset('dashtemplate/css/lib/owl.theme.default.min.css') }}" rel="stylesheet" />



    <link href="{{asset('dashtemplate/css/lib/bootstrap/bootstrap.min.css')}}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/helper.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/style.css') }}" rel="stylesheet">

    

@endsection







@section('content')

<body class="fix-header fix-sidebar">



    <?php $routes = Route::current()->getName() ?>

    @if ( $routes== 'dashboard' || $routes== 'maids-schedule' )

        @include('layouts.dashboard.header')

    @endif





    <div class="container-fluid">



        <div class="row">

            <div class="col-md-4">

                <div class="card p-30">

                    <div class="media">

                        <div class="media-left meida media-middle">

                            <span><i class="fa fa-money f-s-40 color-primary"></i></span>

                        </div>

                        <div class="media-body media-text-right">

                            <h2>{{$income}}</h2>

                            <p class="m-b-0" style="font-size:18px;">Total Income</p>

                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>

                        </div>

                    </div>

                </div>

            </div>

            <div class="col-md-4">

                <div class="card p-30">

                    <div class="media">

                        <div class="media-left meida media-middle">

                            <span><i class="fa fa-archive f-s-40 color-success"></i></span>

                        </div>

                        <div class="media-body media-text-right">

                            <h2>{{$bmaids}}</h2>

                            <p class="m-b-0" style="font-size:18px;">Booked Maids</p>

                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>

                        </div>

                    </div>

                </div>

            </div>



            <div class="col-md-4">

                <div class="card p-30">

                    <div class="media">

                        <div class="media-left meida media-middle">

                            <span><i class="fa fa-archive f-s-40 color-danger"></i></span>

                        </div>

                        <div class="media-body media-text-right">

                            <h2>{{$bcustomers}}</h2>

                            <p class="m-b-0" style="font-size:18px;">Booked Customers</p>

                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </div>



    <div id="appOne"> <dashpaginate></dashpaginate></div>



       

    </div>



    <?php $routes = Route::current()->getName() ?>

    @if ( $routes== 'dashboard' || $routes== 'maids-schedule' )

        @include('layouts.dashboard.footer')

    @endif

    

</body>

@endsection



@section('content-scripts')

    <script src="{{ asset('dashtemplate/js/lib/jquery/jquery.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/custom.min.js') }}"></script>

    <script src="{{ asset('js/app.js') }}" type="text/javascript"></script>



    <!-- Bootstrap tether Core JavaScript -->

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/popper.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- slimscrollbar scrollbar JavaScript -->

    <script src="{{ asset('dashtemplate/js/jquery.slimscroll.js') }}"></script>

    <!--Menu sidebar -->

    <script src="{{ asset('dashtemplate/js/sidebarmenu.js') }}"></script>

    <!--stickey kit -->

    <script src="{{ asset('dashtemplate/js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>

    <!--Custom JavaScript -->

    <script src="{{ asset('dashtemplate/js/lib/morris-chart/morris.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/morris-chart/raphael-min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/calendar-2/moment.latest.min.js') }}"></script>

    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/lib/calendar-2/semantic.ui.min.js') }}"></script>

    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/lib/calendar-2/prism.min.js') }}"></script>

    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/lib/calendar-2/pignose.calendar.min.js') }}"></script>

    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/lib/calendar-2/pignose.init.js') }}"></script>



    <script src="{{ asset('dashtemplate/js/lib/owl-carousel/owl.carousel.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/owl-carousel/owl.carousel-init.js') }}"></script>



    <!-- scripit init-->





@endsection

resources/views/dashboard_backup.blade.php

@extends('layouts.app')

@section('content-styles')
    <!-- Custom CSS -->
    <link href="{{ asset('dashtemplate/css/lib/chartist/chartist.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashtemplate/css/lib/calendar2/semantic.ui.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashtemplate/css/lib/calendar2/pignose.calendar.min.css') }}" rel="stylesheet">
    <link href="{{ asset('dashtemplate/css/lib/owl.carousel.min.css') }}" rel="stylesheet" />
    <link href="{{ asset('dashtemplate/css/lib/owl.theme.default.min.css') }}" rel="stylesheet" />

    <link href="{{asset('dashtemplate/css/lib/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    <link href="{{ asset('dashtemplate/css/helper.css') }}" rel="stylesheet">
    <link href="{{ asset('dashtemplate/css/style.css') }}" rel="stylesheet">
    
@endsection



@section('content')
<body class="fix-header fix-sidebar">

    <?php $routes = Route::current()->getName() ?>
    @if ( $routes== 'dashboard' || $routes== 'maids-schedule' )
        @include('layouts.dashboard.header')
    @endif


    <div class="container-fluid">

        <div class="row">
            <div class="col-md-4">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-usd f-s-40 color-primary"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>{{$income}}</h2>
                            <p class="m-b-0" style="font-size:18px;">Total Income</p>
                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-archive f-s-40 color-success"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>{{$bmaids}}</h2>
                            <p class="m-b-0" style="font-size:18px;">Booked Maids</p>
                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card p-30">
                    <div class="media">
                        <div class="media-left meida media-middle">
                            <span><i class="fa fa-archive f-s-40 color-danger"></i></span>
                        </div>
                        <div class="media-body media-text-right">
                            <h2>{{$bcustomers}}</h2>
                            <p class="m-b-0" style="font-size:18px;">Booked Customers</p>
                            <span style="color:#99abb4;font-size: 13px;">for the last 7 days</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>

            <div class="row">
                @foreach($pagiante as $list)
                <div class="col-md-6">
                    <div class="hpanel">
                            <div class="v-timeline vertical-container animate-panel"  data-child="vertical-timeline-block" data-delay="1">
                     
                                <div class="vertical-timeline-block">
                                    <div class="vertical-timeline-icon navy-bg">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <div class="vertical-timeline-content">
                                        <div class="p-sm">
                                            <span class="vertical-date pull-right">
                                            <small style="font-size: 100% !important; font-weight: bold;">Cleaning</small>
                                                <br>From: {{ $list->schedule_start->format('h:i A') }}
                                                <br>To: {{ $list->schedule_end->format('h:i A') }}
                                                <br>Date: {{ $list->schedule_start->format('l j F') }}
                                            </span>
                                            <h5>Service #: 
                                                    <span class="text-primary">{{ $list->schedule_code }}</span>
                                            </h5>
                                            <h5>Customer: 
                                                <a href="{{ route('customers.show', $list->customer_id) }}" class="text-primary">
                                                    {{ $list->getCustomer['fullname'] }}
                                                </a>
                                            </h5>
                                            <h5>Maid: 
                                                <a href="{{ route('maids.show', $list->maids_id) }}" class="text-primary">
                                                    {{ $list->getMaid['fullname'] }}
                                                </a>
                                            </h5>
                                            
                                            <h6 style="padding-top:8px;">Appointment Note: </h6>
                                            <p>{{ $list->notes }}</p>
                                        </div>
                                        <div class="panel-footer">
                                                @if($list->completed == 1 )
                                                <h4><span class="label label-success">Done</span></h4>
                                                @elseif($list->completed == 3)
                                                    <span class="label label-warning">On queue</span>
                                                @else
                                                    <span class="label label-danger">Pending</span>
                                                @endif

                                            <span class="vertical-date pull-right">Amount to Pay:
                                                <small style="font-size: 100% !important; font-weight: bold;" class="text-primary">
                                                    {{$list->getSaleSummary['payment_sub']}} AED
                                                </small>
                                            </span>
                                        </div>
                                    </div>
                                </div>

                            </div>
                    </div>
                </div>
                @endforeach    
            </div>

            {{ $pagiante->links() }}

    </div>


    <?php $routes = Route::current()->getName() ?>
    @if ( $routes== 'dashboard' || $routes== 'maids-schedule' )
        @include('layouts.dashboard.footer')
    @endif
    
</body>
@endsection

@section('content-scripts')
    <script src="{{ asset('dashtemplate/js/lib/jquery/jquery.min.js') }}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/popper.min.js') }}"></script>
    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/bootstrap.min.js') }}"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="{{ asset('dashtemplate/js/jquery.slimscroll.js') }}"></script>
    <!--Menu sidebar -->
    <script src="{{ asset('dashtemplate/js/sidebarmenu.js') }}"></script>
    <!--stickey kit -->
    <script src="{{ asset('dashtemplate/js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>
    <!--Custom JavaScript -->
    <script src="{{ asset('dashtemplate/js/lib/morris-chart/morris.js') }}"></script>
    <script src="{{ asset('dashtemplate/js/lib/morris-chart/raphael-min.js') }}"></script>
    <script src="{{ asset('dashtemplate/js/lib/calendar-2/moment.latest.min.js') }}"></script>
    <!-- scripit init-->
    <script src="{{ asset('dashtemplate/js/lib/calendar-2/semantic.ui.min.js') }}"></script>
    <!-- scripit init-->
    <script src="{{ asset('dashtemplate/js/lib/calendar-2/prism.min.js') }}"></script>
    <!-- scripit init-->
    <script src="{{ asset('dashtemplate/js/lib/calendar-2/pignose.calendar.min.js') }}"></script>
    <!-- scripit init-->
    <script src="{{ asset('dashtemplate/js/lib/calendar-2/pignose.init.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/owl-carousel/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('dashtemplate/js/lib/owl-carousel/owl.carousel-init.js') }}"></script>

    <!-- scripit init-->
    <script src="{{ asset('dashtemplate/js/custom.min.js') }}"></script>
<!--     <script src="{{ asset('dashtemplate/js/scripts.js') }}"></script> -->
<script type="text/javascript">


</script>
@endsection


resources/views/home.blade.php
<!-- @extends('layouts.app')
 -->
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection