routes/web.php
<?php
use App\Customer;
use App\User;
use Illuminate\Mail\Markdown;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
route::get('/clear/config', function(){
		Artisan::call('config:clear');
	});

route::get('/clear/cache', function(){
	Artisan::call('cache:clear');
});

route::get('/storage/storage', function(){
	Artisan::call('storage:link');
});

Route::get('/', 'AdminController@index')->name('dashboard');
// Route::get('/', 'Dashbaord@index')->name('landing');
Route::get('/reg', function(){
	return view('auth.register');
});
Route::middleware('auth')->prefix('admin')->group(function () {


route::get('/changePassword', function(){
    $user = User::find(auth::user()->id);
	return view('auth.passwords.reset',$user);
});

Route::post('changePassword','AdminController@showChangePasswordForm')->name('changePassword');

Route::get('/mail', function(){
	return view('mail.test');
});


Route::get('/book', function(){
	return view('booking');
});


// Route::get('/mail', function () {
// 	$data['subject'] = 'test';
// 	$data['name'] = 'pwet';

// 	return view('mail.receipt', $data);
    // $markdown = new Markdown(view(), config('mail.markdown'));
    // return $markdown->render('mail.name');
// });

	Route::get('/dashapi', 'AdminController@dashBoardPaginate');

	Route::get('forbidden', function () {
		return view('layouts.dashboard.forbidden');
	});

	Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');


 	Route::get('/maids-schedule', 'AdminController@maids_schedule')->name('maids-schedule');
 	Route::post('/maids-itinerary', 'AdminController@maids_itinerary')->name('maids-itinerary');

	Route::post('/addMaidsItinerary', 'AdminController@addMaidsItinerary')->name('addMaidsItinerary');
	Route::post('/maids_itinerary_update', 'AdminController@maids_itinerary_update')->name('maids_itinerary_update');
	Route::post('/get_available_maids', 'AdminController@get_available_maids')->name('get_available_maids');
	
	Route::get('/drivers-schedule', 'AdminController@drivers_schedule')->name('drivers-schedule');

	Route::post('/getCountPerAreaMaids', 'AdminController@getCountPerAreaMaids')->name('getCountPerAreaMaids');
	
	Route::any('/getAreaSubArea', 'AdminController@getAreaSubArea')->name('getAreaSubArea');
	
	Route::post('getAreaOnly', 'AdminController@getAreaOnly')->name('getAreaOnly');
	
	Route::post('/getJsonRequestResource', 'AdminController@getJsonRequestResource')->name('getJsonRequestResource');
	Route::post('/getJsonRequestEvent', 'AdminController@getJsonRequestEvent')->name('getJsonRequestEvent');

	Route::post('/getAreaAndCount', 'AdminController@getAreaAndCount')->name('getAreaAndCount');
	Route::post('/getlabel', 'AdminController@getlabel')->name('getlabel');

	Route::post('/procDoneTask', 'AdminController@procDoneTask')->name('procDoneTask');

	Route::post('getamount', 'AdminController@getAmount')->name('getAmount');

	Route::post('getamountwithtax', 'AdminController@getAmountWithTax')->name('getAmountWithTax');

	//maintenance	


	Route::resource('maids', 'AdminMaids');
	Route::resource('drivers', 'AdminDrivers');
	Route::resource('customers', 'AdminCustomers');

	Route::middleware('super')->group(function () {
		//admin maids
		Route::post('/delmaids','AdminMaids@delmaids')->name('delmaids');
		//admin drivers
		Route::post('/deldriver','AdminMaids@deldriver')->name('deldriver');
		//admin users
		Route::resource('users', 'AdminUsers');
		Route::post('/delusers','AdminUsers@delusers')->name('delusers');
		//admin customers
		Route::post('/delcustomer','AdminCustomers@delcustomer')->name('delcustomer');
		Route::post('getareas','AdminCustomers@getareas')->name('getareas');
	});

	//reports
	//sales
	Route::get('/reports/sales', 'AdminSales@index');
	Route::post('year', 'AdminSales@year')->name('year');
	Route::post('week', 'AdminSales@week')->name('week');
	Route::post('month', 'AdminSales@month')->name('month');
	Route::get('/reports/now', 'AdminSales@week');

	Route::get('/sales-test', 'AdminSales@index2');
	Route::post('/daterange', 'AdminSales@dateRange')->name('daterange');
	Route::post('TranSummaryFilter', 'AdminSales@TranSummaryFilter')->name('TranSummaryFilter');
	Route::get('/reports/details', 'AdminSalesDetails@index');

	Route::get('/reports/top-customers','AdminSales@TopCustomers' );
	Route::get('/reports/top-maids','AdminSales@TopMaids' );

	Route::get('/reports/active-customers','AdminSales@ActiveCustomers' );
	Route::get('/reports/inactive-customers','AdminSales@InactiveCustomers' );

	Route::get('/reports/cancelled-appointments', function(){
        return view('parts-dashboard.admin-cancelled-appointments');
	});
	Route::post('CancelledAppoint', 'AdminSales@CancelledAppoint')->name('CancelledAppoint');

	Route::post('ActiveAjax', 'AdminSales@ActiveAjax');
	Route::get('/transactions-customers', 'AdminTransactions@CustomersView');
	Route::post('TransactionTableCustomers', 'AdminTransactions@TransactionTableCustomers')->name('TransactionTableCustomers');
	Route::get('transactions/{id}/customer-transaction','AdminTransactions@TransactionCustomerView');

	Route::get('/transactions-maids', 'AdminTransactions@MaidsView');
	Route::get('transactions/{id}/maid-transaction','AdminTransactions@TransactionMaidView');
	Route::post('TransactionTableMaids', 'AdminTransactions@TransactionTableMaids')->name('TransactionTableMaids');

	Route::get('/appointments', 'AdminBook@index')->name('appointments');
	Route::post('getCUstomerDetails', 'AdminBook@getCUstomerDetails')->name('getCUstomerDetails');
	Route::post('newAppointment', 'AdminBook@newAppointment')->name('newAppointment');
	Route::get('/maids-schedule-table', 'AdminBook@MaidsScheduleTableView');
	Route::post('MaidsScheduleTableDetail', 'AdminBook@MaidsScheduleTableDetail')->name('MaidsScheduleTableDetail');
	Route::post('MaidsScheduleTable', 'AdminBook@MaidsScheduleTable')->name('MaidsScheduleTable');
	Route::post('MaidsScheduleTableCancel', 'AdminBook@MaidsScheduleTableCancel')->name('MaidsScheduleTableCancel');
	Route::any('/MaidsScheduleRecur', 'AdminBook@MaidsScheduleRecur')->name('MaidsScheduleRecur');
	Route::post('editAppointment', 'AdminBook@editAppointment')->name('editAppointment');
	Route::post('getamountRecur', 'AdminController@getamountRecur')->name('getamountRecur');
	Route::post('/appointments', 'AdminBook@quickAdd')->name('quickAdd');
	Route::post('quickEdit', 'AdminBook@quickEdit')->name('quickEdit');

	Route::get('/cancel-appointment', function(){
		return view('parts-dashboard.admin-cancel-appointment');
	});
	
	Route::post('cancelAppointment', 'AdminBook@cancelAppointment')->name('cancelAppointment');
	Route::get('/paginate', 'AdminPaginate@index');
	Route::get('/paginate/dropdown/{id}/fullname/{name}/api', 'AdminPaginate@returnApi');
	Route::get('/paginate/getDropdown','AdminPaginate@getDropdown');
	Route::get('/paginate/maids/api','AdminPaginate@returnApiMaids');

	Route::get('/accounting', 'AdminAccounting@index');
	Route::get('/accounting-paid', 'AdminAccounting@paidView');
	Route::get('/accounting-unpaid', 'AdminAccounting@unpaidView');
	Route::post('AccountingType', 'AdminAccounting@AccountingType')->name('AccountingType');
	Route::post('AccountingTable', 'AdminAccounting@AccountingTable')->name('AccountingTable');
	Route::get('/accounting/{id}/transaction-details','AdminAccounting@TransactionDetails');
	Route::post('sendEmailAccount', 'AdminAccounting@sendEmailAccount')->name('sendEmailAccount');

	Route::post('checkBalance', 'AdminAccounting@checkBalance')->name('checkBalance');
	Route::post('savepayment', 'AdminAccounting@savepayment')->name('savepayment');
	Route::post('payAllSumId', 'AdminAccounting@payAllSumId')->name('payAllSumId');
	Route::post('payPerSumId', 'AdminAccounting@payPerSumId')->name('payPerSumId');
	Route::get('/accounting/{id}/transaction-details/pdf','AdminAccounting@exporting');

	Route::post('sendEmail', 'MailController@sendEmail')->name('sendEmail');

	Route::get('/invoice', 'AdminAccounting@invoice');
	// Route::get('/mail', 'AdminAccounting@mail');

	Route::post('sendEmailReceipt', 'AdminAccounting@sendEmailReceipt')->name('sendEmailReceipt');
	Route::post('emailCustomers', 'AdminSales@emailCustomers')->name('emailCustomers');

	Route::get('/products', function(){
		return view('parts-dashboard.admin-products');
	});



});

resources/views/parts-dashboard/drivers-details.blade.php
@extends('layouts.app')



@section('content-styles')

    <!-- Custom CSS -->



    <link href="{{ asset('dashtemplate/css/lib/owl.theme.default.min.css') }}" rel="stylesheet" />

    <link href="{{asset('dashtemplate/css/lib/bootstrap/bootstrap.min.css')}}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/helper.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/style.css') }}" rel="stylesheet">

    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">





@endsection



@section('content')

<body class="fix-header fix-sidebar">



@include('layouts.dashboard.header')



                                                                                                                                                        

<div class="container-fluid" id="formaids">





<!-- Start Page Content -->

    <div class="row">

        <div class="col-md-12">

            <div class="card">

                <div class="card-body">

                    <div class="row">

                        <div class="col-lg-12">

                            <div id="invoice" class="effect2">

                                <div id="invoice-top">

                                                    

                                    <div class="clientlogo">

                                        @if($ddata->photo != '')

                                        <img src= " {{ asset('storage/drivers').'/'.$ddata->photo }}" >

                                        @endif

                              



                                    </div>

                                    <div class="invoice-info">

                                        <h3 class="text-primary">{{$ddata->fullname}}</h3>

                                        <hr>

                                        <p > 

                                            <i class="fa fa-birthday-cake" aria-hidden="true"></i>

                                                {{$ddata->birthdate->format('Y-m-d')}}

                                        </p>

                                        <p> 

                                            <i class="fa fa-venus-mars" aria-hidden="true"></i>

                                                {{ $ddata->gender == "1" ? "Female" : "Male" }}

                                       </p>

                                        <p> 

                                            <i class="fa fa-mobile" aria-hidden="true"></i>

                                                {{$ddata->mobile}}

                                       </p>

                                    </div>

                                    <!--End Info-->

                

                                    <div class="title col-md-4 text-center booking">

                                        <h4 class="text-danger">Booking Summary</h4>

                                            <hr>

                                            <div class="row">

                                                <div class="col-sm-6 "> 

                                                    <p>TOTAL BOOKINGS:</p>

                                                </div>

                                            

                                                <div class="col-sm-6 ">

                                                    <p class="text-primary">{{$hours['totalbooked']}}</p>

                                                </div>

                                            </div>

                                     

                                            <div class="row">

                                                 <div class="col-sm-6 ">

                                                    <p>WORKING HOURS:</p>

                                                </div>



                                                 <div class="col-sm-6 ">

                                                    <p class="text-primary">{{$ddata->shift_start}} - {{$ddata->shift_end}}</p>

                                                </div>

                                            </div>

                                        

                                            <div class="row">

                                                 <div class="col-sm-6 ">

                                                    <p>HOURS WORKED:</p>

                                                </div>

                                                 <div class="col-sm-6">

                                                    <p class="text-primary">{{$hours['totalhours']}}</p>

                                                </div>

                                            </div>



                                    </div>

                                  

                                </div>

                        

                                <div id="invoice-bot">

                                    <div class="table-responsive m-t-40">

                                      

                                        <div class="table-responsive m-t-40">

                                            <h4 class="text-primary">Bookings</h4>  

                                            <table id="myTablemaid" class="table table-bordered table-striped">

                                                <thead>

                                                    <tr>

                                                        <th>Service #</th>

                                                        <th>Booking Date</th>

                                                        <th>Time</th>

                                                        <th>Client</th>

                                                        <th>Status</th>

                                         

                                                    </tr>

                                                </thead>

                                                <tbody>

                                                    @foreach($dsched as $list)

                                                    <tr>

                                                        <td>{{$list['schedule_code']}}</td>

                                                        <td>{{$list['schedule_start']}}</td>

                                                        <td>{{$list['time']}}</td>

                                                            <td>

                                                                <a class="text-primary" href="{{ route('customers.show', $list['customer_id']) }}">{{$list['client']}}</a>

                                                            </td>

                                                        <td>

                                                            @if($list['status'] == '1' )

                                                                <span class="label label-success">Done</span>

                                                            @elseif($list['status'] == '3')

                                                                <span class="label label-warning">On queue</span>

                                                            @else

                                                                <span class="label label-danger">Canceled</span>

                                                            @endif

                                                        </td>

                                                       

                                                    </tr>

                                                    @endforeach

                                                </tbody>

                                            </table>

                                        </div>

                                    </div>       

                                </div>

                           

                            </div>

                            <a class="pull-right" href="{{ route('maids.index') }}"><button class="btn btn-success">Back</button></a>

                       

                        </div>



                    </div>

                </div>

            </div>

        </div>

    </div>

    <!-- End PAge Content -->



</div>



    @include('layouts.dashboard.footer')

                                                                                                                                                                                                                                                                                                                                                                                                         

</body>



@endsection



@section('content-scripts')

    <script src="{{ asset('dashtemplate/js/lib/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap tether Core JavaScript -->

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/popper.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- slimscrollbar scrollbar JavaScript -->

    <script src="{{ asset('dashtemplate/js/jquery.slimscroll.js') }}"></script>

    <!--Menu sidebar -->

    <script src="{{ asset('dashtemplate/js/sidebarmenu.js') }}"></script>

    <!--stickey kit -->

    <script src="{{ asset('dashtemplate/js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>

    <!--Custom JavaScript -->



    <!-- fullcalendar -->    

    <script src="{{ asset('dashtemplate/fullcalendar/lib/moment.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/fullcalendar/lib/fullcalendar.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/fullcalendar/scheduler.min.js') }}"></script>



    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/custom.min.js') }}"></script>



    <script src="{{ asset('dashtemplate/js/lib/datatables/datatables.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/datatables-init.js') }}"></script>





    <script src="{{ asset('vue/dist/vue.js') }}"></script>

    <script src="{{ asset('vue/dist/vue.min.js') }}"></script>



    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/vue.resource/0.9.3/vue-resource.min.js"></script>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>





@endsection

resources/views/parts-dashboard/maids-add.blade.php
@extends('layouts.app')



@section('content-styles')

    <!-- Custom CSS -->



    <link href="{{ asset('dashtemplate/css/lib/owl.theme.default.min.css') }}" rel="stylesheet" />

    <link href="{{asset('dashtemplate/css/lib/bootstrap/bootstrap.min.css')}}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/helper.css') }}" rel="stylesheet">

    <link href="{{ asset('dashtemplate/css/style.css') }}" rel="stylesheet">

    <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">





@endsection



@section('content')

<body class="fix-header fix-sidebar">



    <?php $routes = $routes = Request::segment(3); ?>

    @if ( $routes== 'create'  )

        @include('layouts.dashboard.header')

    @endif                                                                                                                                                             



<div class="container-fluid" id="formaids" style="padding-top: 20px;">

    <div class="panel-body">

        <form method="POST" enctype="multipart/form-data" action="{{route('maids.store')}}" novalidate>

        @csrf

        <div class="row">

            <div class="col-md-12">

                <div class="row">

                    <div class="col-md-3">

           

                        <img style="cursor: pointer;width:100%"  onclick="$('#photo').trigger('click')"  id="cur_img" 

                        class="img img-thumbnail img-responsive" src="{{ asset('img/default_big.png') }}">

                        <p class="text-center">( Click to browse image )</p>

                        <input class="hide" type="file" name="photo" id="photo">



                    </div>

                    <div class="col-md-9">

                        <div class="row">

                            <div class="col-md-12">

                                <div class="hpanel">

                                    <div class="panel-heading" style="padding-bottom: 20px;">

                                        <span><i class="fa fa-user"></i> Personal Information</span></div>

                                    <div class="panel-body">

                                        <div class="row">

                                            <div class="col-md-8">

                                                <div class="form-group">

                                                    <label>First Name <span class="required">*</span></label>

                                                    <input required="" name="fullname" type="text" 

                                                    class="form-control" autocomplete="off">

                                                </div>

                                            </div>

                                            <div class="col-md-3">

                                                <div class="form-group">

                                                    <label class="control-label">Gender</label>

                                                    <select class="form-control custom-select" name="gender" required="required">

                                                        <option value="">--select--</option>

                                                        <option value="2">Male</option>

                                                        <option value="1">Female</option>

                                                    </select>            

                                                </div>

                                            </div>

                                        </div>

                                        <div class="row">

                                            <div class="col-md-6">

                                                <div class="form-group">

                                                    <label class="control-label">Date of Birth</label>

                                                    <input type="date"  class="form-control" name="birthdate" 

                                                    id="birthdate" autocomplete="off" 

                                                    required="required">

                                                </div>

                                            </div>

                                        </div>

                                        <div class="row">

                                            <div class="col-md-6">

                                                <div class="form-group">

                                                    <label>Mobile Number <span class="required">*</span></label>

                                                    <input required="" name="mobile" 

                                                    type="text" class="form-control" value="@{{mobile}}" required="required" 

                                                    placeholder="+971" maxlength="13" autocomplete="off">

                                                </div>

                                            </div>



                                        </div>

                                        <div class="row">



                                            <div class="col-md-3">

                                                <div class="form-group">

                                                    <label class="control-label">Shift Start</label>

                                                    <input type="time" class="form-control" name="shift_start" 

                                                    id="shift_start" autocomplete="off" 

                                                    required="required">

                                                </div>

                                            </div>



                                            <div class="col-md-3">

                                                <div class="form-group">

                                                    <label class="control-label">Shift End</label>

                                                    <input type="time"  class="form-control" name="shift_end" 

                                                    id="shift_end" autocomplete="off" 

                                                    required="required">

                                                </div>

                                            </div>



                                        </div>

                                    </div>

                                </div>

                            </div>

                        </div>

                    </div>

                </div>

                <div class="form-group">

                    <button class="btn btn-primary" id="btnsubmit" type="submit"><i class="fa fa-save"></i> Save Maid</button>

                    <a href="{{ route('maids.index') }}" class="btn btn-default"><i class="fa fa-times"></i> Cancel</a>

                </div>

            </div>      

        </div>

        </form>            

    </div>



</div>



    <?php $routes = $routes = Request::segment(3); ?>

    @if ( $routes== 'create'  )

        @include('layouts.dashboard.footer')

    @endif                                                                                                                                                                                                                                                                                                                                                                                                            

</body>



@endsection



@section('content-scripts')

    <script src="{{ asset('dashtemplate/js/lib/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap tether Core JavaScript -->

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/popper.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/bootstrap/js/bootstrap.min.js') }}"></script>

    <!-- slimscrollbar scrollbar JavaScript -->

    <script src="{{ asset('dashtemplate/js/jquery.slimscroll.js') }}"></script>

    <!--Menu sidebar -->

    <script src="{{ asset('dashtemplate/js/sidebarmenu.js') }}"></script>

    <!--stickey kit -->

    <script src="{{ asset('dashtemplate/js/lib/sticky-kit-master/dist/sticky-kit.min.js') }}"></script>

    <!--Custom JavaScript -->



    <!-- fullcalendar -->    

    <script src="{{ asset('dashtemplate/fullcalendar/lib/moment.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/fullcalendar/lib/fullcalendar.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/fullcalendar/scheduler.min.js') }}"></script>



    <!-- scripit init-->

    <script src="{{ asset('dashtemplate/js/custom.min.js') }}"></script>



    <script src="{{ asset('dashtemplate/js/lib/datatables/datatables.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js') }}"></script>

    <script src="{{ asset('dashtemplate/js/lib/datatables/datatables-init.js') }}"></script>





    <script src="{{ asset('vue/dist/vue.js') }}"></script>

    <script src="{{ asset('vue/dist/vue.min.js') }}"></script>



    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/vue/1.0.26/vue.min.js"></script>

    <script type="text/javascript" src="https://cdn.jsdelivr.net/vue.resource/0.9.3/vue-resource.min.js"></script>

    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">



    $(document).ready(function(){



        $("#photo").change(function () {

            readURL(this);

        });



        function readURL(input) {

            if (input.files && input.files[0]) {

                var reader = new FileReader();



                reader.onload = function (e) {

                    // alert(e.target.result);

                    $('#cur_img').attr('src', e.target.result);

                }



                reader.readAsDataURL(input.files[0]);

            }

        }





    }); 





    Vue.http.headers.common['X-CSRF-TOKEN'] = $('meta[name="csrf-token"]').attr('content');

    new Vue({



        el: '#formaids',



        data: {



            mobile : '+971'





        },



        methods : {



        }







    });



    </script>



@endsection